# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categorys', verbose_name='Photo')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Wikipedia Link')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
    ]
