# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('-pk',), 'verbose_name': 'observation', 'verbose_name_plural': 'observations'},
        ),
        migrations.AddField(
            model_name='observation',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
